replicaCount: 1

image:
  repository: loadinggreg/tech-challenge
  pullPolicy: IfNotPresent
  tag: "latest"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  project: software-architecture-fiap

podLabels:
  app: tech-challenge-app

service:
  port: 8080
  nodePort: 30808
  type: NodePort

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"

#This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

database:
  host: tech-challenge-database-mysql

