apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-admin-secret
  namespace: tech-challenge
  labels:
    app: tech-challenge-admin
data: ## colocar tudo em base64
  DB_PORT: 'MzMwNg==' # 3306
  DB_USER: 'dGVjaC11c2Vy' # tech-user
  DB_PASSWORD: 'dGVjaC1wYXNz' # tech-pass
  DB_NAME: 'dGVjaC1jaGFsbGVuZ2U=' #tech-challenge
  DB_ROOT_PASSWORD: 'dGVjaC1wYXNz' # tech-pass
  KEY_MERCADO_PAGO: 'QVBQX1VTUi0yMjk0MzIzNzU5OTY0MDQyLTAxMTIxNC1mZTI3ODc2NDA4MjNmYjY2ZDU3Y2U3YzI3ZGRlNjBkNi0yMjAyNTA0Nzg3' # mercado pago key